name: Packer Build

on:
  push
      
jobs:
  CheckVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 获取当前版本
        run: |
          cat version.pkrvars.hcl
          echo `cat version.pkrvars.hcl` > $GITHUB_ENV
          
      - name: 获取最新版本
        run: |
          new_version=$(curl -s https://api.github.com/repos/WordPress/WordPress/tags | jq '.[0].name')
          echo "new_version = "$new_version > $GITHUB_ENV
          
      - name: 保存新版本
        if: ${{ env.Application_Version }} == ${{ env.new_version }}
        run: |
          echo "Application_Version = "$new_version > version.pkrvars.hcl
