name: Packer Build

on:
  push
      
jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # github 认证
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://virain:${{ secrets.PERSONAL_TOKEN }}@github.com/

      - name: 获取当前版本
        run: |
          cat version.pkrvars.hcl
          echo `cat version.pkrvars.hcl` > $GITHUB_ENV
          
      - name: 获取最新版本
        run: |
          new_version=$(curl -s https://api.github.com/repos/WordPress/WordPress/tags | jq '.[0].name')
          echo "new_version="$new_version > $GITHUB_ENV
          
      - name: 保存新版本
        if: ${{ env.Application_Version!=env.new_version }}
        id: has_new_version
        run: |
          echo 'Application_Version=${{ env.new_version }}' > version.pkrvars.hcl
          git config --local user.email "xu_junkai@hotmail.com"
          git config --local user.name "virain"
          git commit -m  "update $(echo ${{ env.new_version }})" -a
          git push
          echo "::set-output name=has_new_version::true"
        
    outputs: 
      has_new_version: ${{ steps.has_new_version.outputs.has_new_version }}
      
  Build:
    runs-on: ubuntu-latest
    needs: CheckVersion
    if: ${{ needs.CheckVersion.outputs.has_new_version == 'true' }} # 是否有新版本
    strategy:
      matrix:
        phpenv: 
          - LNMP
          - LAMP
        cloud:
          - alicloud-ecs
          - tencentcloud-cvm
        release:
          - CentOS
          - Ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: packer build
        run: echo "packer build --only='$cloud.$phpenv\_$release' -var-file=version.pkrvars.hcl packer.hcl "
        env:
          phpenv: ${{ matrix.phpenv }}
          cloud: ${{ matrix.cloud }}
          release: ${{ matrix.release }}